name: Release version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: pip install requests wheel twine
    - name: Upload package
      run: |
        python upload.py ${{ secrets.PYPIUSER }} ${{ secrets.PYPIPWD }}
