name: Python Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install pytest coverage
    - name: Test with unittest
      run: |
        coverage run -p -m unittest tests/test_alias.py
        coverage run -p -m unittest tests/test_basic.py
        coverage run -p -m unittest tests/test_ignore.py
        coverage run -p -m unittest tests/test_options.py
        coverage run -p -m unittest tests/test_params.py
        coverage run -p -m unittest tests/test_input.py
        coverage run -p -m unittest tests/test_complex.py
        coverage combine
        coverage report
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash) -F